cookie:
  expiry_days: 30
  key: a_random_signature_key_change_me
  name: my_app_auth_cookie
credentials:
  usernames:
    ronitsawaiyan:
      email: sawaiyanronit12@gmail.com
      failed_login_attempts: 0
      first_name: Ronit
      last_name: Sawaiyan
      logged_in: false
      password: ronit123
      roles:
      - admin
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$rOFha7FlRjHZ4iAwvs5vluhbuMSer1aacZjUbXqYgDa.KNOtkrul6
      roles:
      - viewer
pre-authorized:
  emails:
  - newuser@example.com
  - sawaiyanronit12@gmail.com
